project_id = "qnrgymppanngkpwsgqrx"

[analytics]
  enabled = false
  gw_port = 54329
  port = 54327
  vector_port = 54328

[api]
  enabled = true
  extra_search_path = ["public", "extensions"]
  max_rows = 1000
  port = 54321
  schemas = ["public", "graphql_public"]

[auth]
  additional_redirect_urls = ["https://127.0.0.1:3000"]
  enable_email_autoconfirm = false
  enable_email_confirmations = false
  enable_phone_autoconfirm = false
  enable_phone_confirmations = false
  enable_signup = true
  enabled = true
  jwt_expiry = 3600
  port = 54329
  site_url = "http://127.0.0.1:3000"
  [auth.email]
    double_confirm_changes = true
    enable_confirmations = false
    enable_signup = true
    [auth.email.template]
  [auth.sms]
    enable_confirmations = false
    enable_signup = false
    template = "Your code is {{ .Code }}"

[db]
  major_version = 15
  port = 54322
  shadow_port = 54320
  [db.pooler]
    default_pool_size = 20
    enabled = false
    max_client_conn = 100
    pool_mode = "transaction"
    port = 54329

[edge_functions]
  enabled = true
  ip_version = "ipv4"
  port = 54330

[functions]
  [functions.ai-chat]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-drip]
    verify_jwt = false
  [functions.schedule-email-drip]
    verify_jwt = false
  [functions.send-welcome-email]
    verify_jwt = false
  [functions.subscribe-newsletter]
    verify_jwt = false

[inbucket]
  enabled = true
  pop3_port = 54327
  port = 54325
  smtp_port = 54326

[realtime]
  enabled = true
  ip_version = "ipv4"
  port = 54323

[storage]
  enabled = true
  file_size_limit = "50MiB"
  image_transformation = true
  port = 54328

[studio]
  api_url = "http://127.0.0.1:54321"
  enabled = true
  openai_api_key = "env(OPENAI_API_KEY)"
  port = 54324
