// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnrgymppanngkpwsgqrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucmd5bXBwYW5uZ2twd3NncXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTg5MDksImV4cCI6MjA3MzM5NDkwOX0.ti0ajcafxMhqaPLt1iEUmGnEETMVXVCF3cvZTw65lKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});